### ISSUE TITLE
Theme removes background on restart

### ISSUE THREAD

**Issue by lifebarier** [jonathanlermitage/intellij-darcula-sombre-theme#1]
It seems that every time I restart intellij with this theme selected it removes background that was set (ctrl+shift+a - set background image). Does not happen with standard Dracula theme. Intellij ultimate 19.1.1

**Comment by jonathanlermitage** [comment]
Thx for reporting this issue. I'll look at this asap.

**Comment by jonathanlermitage** [comment]
It seems to be a bug in IntelliJ. I faced the same issue with:
* an other custom theme (Dark purple)
* a new theme that customize nothing

**Comment by jonathanlermitage** [comment]
Confirmed: https://youtrack.jetbrains.com/issue/IDEA-211541

It seems to be fixed in 2019.1.2

**Comment by jonathanlermitage** [comment]
Fix confirmed, it works fine with IJ 2019.1.2 RC
